### ISSUE TITLE
[BUG] DatasetGen doesn't work with cudf>22.06

### ISSUE THREAD

**Issue by benfred** [NVIDIA-Merlin/NVTabular#1653]
The DatasetGen class doesn't work with cudf 22.06+ - since it uses the 'ceil' function on series that was removed in cudf:  https://github.com/rapidsai/cudf/issues/11331

This causes unittest failures like

```
FAILED tests/unit/test_tools.py::test_powerlaw[None-1000] - AttributeError: 'Series' object has no attribute 'ceil'
```

**Comment by benfred** [comment]
Fixed by #1656
