### ISSUE TITLE
hash_object-dispatch issue with rapids 21.08 and 0.7.0/0.5.3

### ISSUE THREAD

**Issue by meprem** [NVIDIA-Merlin/NVTabular#1151]
`
---> 
21 import nvtabular as nvt 22 23 from cudf.io.parquet import ParquetWriter~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/nvtabular/__init__.py in <module> 16 import warnings 17 
---> 18 from . import column_group, io, workflow # noqa 
19 from ._version import get_versions 20 

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/nvtabular/column_group.py in <module> 18 from dask.core import flatten 19 ---> 20 from nvtabular.ops import LambdaOp, Operator 21 22 ~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/nvtabular/ops/__init__.py in <module> 17 # alias submodules here to avoid breaking everything with moving to submodules 18 # flake8: noqa---> 19 from .bucketize import Bucketize 20 from .categorify import Categorify, _get_embedding_order, get_embedding_sizes 21 from .clip import Clip~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/nvtabular/ops/bucketize.py in <module> 16 from nvtx import annotate 17 ---> 18 from .operator import ColumnNames, Operator 19 20 ~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/nvtabular/ops/operator.py in <module> 18 from typing import TYPE_CHECKING, List, Optional, Union 19 ---> 20 from nvtabular.dispatch import DataFrameType 21 22 if TYPE_CHECKING:~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/nvtabular/dispatch.py in <module> 25 from cudf.core.column import as_column, build_column 26 from cudf.utils.dtypes import is_list_dtype---> 27 from dask.dataframe.utils import hash_object_dispatch 28 29 DataFrameType = Union[pd.DataFrame, cudf.DataFrame]ImportError: cannot import name 'hash_object_dispatch' from 'dask.dataframe.utils' (/home/ubuntu/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/dask/dataframe/utils.py)
`

**Comment by benfred** [comment]
Thanks for the bug report - Can you let me know how are you installing NVTabular? Also what version of dask are you using ?

**Comment by benfred** [comment]
You'll need a newer version of NVTabular to work with the version of dask/cudf you're installing. We added code to fix this error in NVTabular 0.6.0 - and work with dask >= 2021.05.0 : 

https://github.com/NVIDIA/NVTabular/blob/886d5b85fee83acfefc3f60c282f723f41719d53/nvtabular/dispatch.py#L40-L45

Can you try again installing the latest version of NVTabular (v0.7.0)?
