### ISSUE TITLE
[QST] v0.7.0 does not have .columns feature & other issues upgrading version

### ISSUE THREAD

**Issue by gaceladri** [NVIDIA-Merlin/NVTabular#1231]
I am trying to update my version of NVTabular in order to benefit from the improvements done from version 0.5.1 and trying to leave it as a more robust workflow. The question is that you use a lot:

`var_x = [x for x in groupby_other_features.columns if x!= 'whatever']`

but in version 0.7.0 you can not get the name of the columns like `.columns` because you get:

`AttributeError: 'WorkflowNode' object has no attribute 'columns'`

Do you mind how to refactor the code in order to work in v0.7.0? 

And also, you created [a custom Op in solving this competition](https://github.com/NVIDIA-Merlin/competitions/blob/main/SIGIR_eCommerce_Challenge_2021/task1_session_based_rec/1-preprocessing/ecom_preproc_step1.ipynb) that suffers from the same, that you can not iterate over columns:
```
from nvtabular.ops import Operator

class ItemRecency(Operator):
    def transform(self, columns, gdf):
        for column in columns:
            col = gdf[column]
            #col.loc[col == ""] = None
            item_first_timestamp = gdf['itemid_ts_first']
            delta_days = (col - item_first_timestamp).dt.days
            gdf[column + "_age_days"] = delta_days * (delta_days >=0)
        return gdf
            
    def output_column_names(self, columns):
        return [column + "_age_days" for column in columns]
            
    def dependencies(self):
        return ["itemid_ts_first"]
```

gives the next error: 
`TypeError: 'ColumnSelector' object is not iterable`

Do you mind how to also solve that in v0.7.0? 

Thanks!

**Comment by benfred** [comment]
We made some pretty big changes in the 0.7 API .

To get columns out of nodes in the graph, you'll have to make sure that ```workflow.fit``` or ```workflow.fit_schema``` is called on a dataset first. After that has happened, you can either get the columns being produced by the node with ```groupby_other_features.output_columns``` or the columns being consumed by the node with ```groupby_other_features.input_columns```.

For the ItemReceny operator, you'll need to make a minor change to the ```output_column_names``` function:

```python
    def output_column_names(self, columns):
        return [column + "_age_days" for column in columns.names]
```

There is an example with this here: https://nvidia-merlin.github.io/NVTabular/main/examples/advanced-ops-outbrain/02-ETL-with-NVTabular.html#Feature-Engineering

**Comment by gaceladri** [comment]
At some point do you plan to update the competition solutions to the new 0.7 API? i'm back to 0.5.1 because i've been trying to upgrade it for 2 days. Unfillable without documentation :( I was trying to hardcode the columns that the V0.5.1 printed here `remaining_columns = [x for x in groupby_other_features.columns if x!= 'timestamp-first']` but then, it does not recognize any column in that hardcoded list. Very strange.
